// <auto-generated />
using ConnectionsTest.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ConnectionsTest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180628143246_newModelForBooks")]
    partial class newModelForBooks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConnectionsTest.Model.Books", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BooksAuthor");

                    b.Property<string>("BooksTitle");

                    b.Property<int>("StarRating");

                    b.HasKey("ID");

                    b.ToTable("BookItems");
                });

            modelBuilder.Entity("ConnectionsTest.Model.Connections", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConnectionDescription");

                    b.Property<string>("ConnectionName");

                    b.Property<int>("StarRating");

                    b.HasKey("ID");

                    b.ToTable("ConnectionItems");
                });
#pragma warning restore 612, 618
        }
    }
}
